name: reusable workflow-1
on:
  workflow_call:
    inputs:
      message:
        description: 'The message to log'
        required: true
        type: string

jobs:
  run-job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: write something to log
        run: |
          echo "${{ inputs.message }}"
